linux追加

diff --git a/.github/workflows/test-linux.yml b/.github/workflows/test-linux.yml
--- a/.github/workflows/test-linux.yml
+++ b/.github/workflows/test-linux.yml
@@ -1,16 +1,17 @@
-name: Test OSX
+name: Test Linux
 
 on: 
   push:
     branches:
       - master
       - develop
+  pull_request:
 
 jobs:
-  test-osx:
+  test-linux:
     env:
       REPOSITORY_NAME: Test
-    runs-on: macOS-latest
+    runs-on: ubuntu-latest
     steps:
 
     - name: Checkout
@@ -29,9 +30,6 @@ jobs:
         submodules: recursive
         lfs: true
 
-    - name: Select Xcode version
-      run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app/Contents/Developer'
-
     - name: Projucer Setting
       run: |
         chmod 755 ./lib/ProjucerPackage/osx/setup.sh
@@ -39,15 +37,18 @@ jobs:
         ./lib/ProjucerPackage/osx/Projucer --resave "./Test/$REPOSITORY_NAME.jucer"
 
     - name: Build
-      run: 
-        xcodebuild -project "Test/Builds/MacOSX/$REPOSITORY_NAME.xcodeproj" -scheme "$REPOSITORY_NAME - App" -configuration Debug build
-
-    - name: Run Test
       run: |
-        lldb -s ./bin/lldb_command.script "./Test/Builds/MacOSX/build/Debug/$REPOSITORY_NAME.app" > test.log
-        if [$(grep "All tests completed successfully" test.log) = ""]; then
-          echo "Test Failed"
-          exit 1;
-        else
-          echo "Test Succeed"
-        fi
+        cd Test/Builds/LinuxMakefile
+        make
+        ls
+        # xcodebuild -project "Test/Builds/MacOSX/$REPOSITORY_NAME.xcodeproj" -scheme "$REPOSITORY_NAME - App" -configuration Debug build
+
+    # - name: Run Test
+    #   run: |
+    #     lldb -s ./bin/lldb_command.script "./Test/Builds/Linux/build/Debug/$REPOSITORY_NAME" > test.log
+    #     if [$(grep "All tests completed successfully" test.log) = ""]; then
+    #       echo "Test Failed"
+    #       exit 1;
+    #     else
+    #       echo "Test Succeed"
+    #     fi
